# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: md5

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # login area for backoffice users
        backend:
            context: primary_auth
            pattern:            ^/admin
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                failure_path:   admin_homepage
                default_target_path: admin_homepage
            logout:
                path: fos_user_security_logout
                target: main_homepage
            anonymous:    true

    access_control:
            # back-office
            - { path: ^/[^/]+/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[^/]+/admin, roles: ROLE_ADMIN }
            - { path: ^/[^/]+/sadmin, roles: ROLE_SUPER_ADMIN }
            - { path: ^/[^/]+/private, roles: ROLE_USER }
            # front-office
            - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[^/]+/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[^/]+/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[^/]+/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[^/]+/profile, role: IS_AUTHENTICATED_FULLY }
            - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }